### ISSUE TITLE
Error while 'Save & Publish' of newly created page on SS 3.2.* and 3.3.*

### ISSUE THREAD

**Issue by hdpero** [titledk/silverstripe-uploaddirrules#7]
We find out that there is an error while trying to Save and Publish a new Page on Silverstripe versions 3.2.\* and 3.3.\* .

We tried to come up with solution, and narrow it down to line 95 on [AssetsFolderExtension.php](https://github.com/titledk/silverstripe-uploaddirrules/blob/master/code/AssetsFolderExtension.php)
That line makes 2 versions on page creation on Page_versions database table.
So if you try to Save and Publish a new Page error is shown with description:
`Duplicate entry '125-2' for key 'RecordID_Version'`

Best,
Petar

**Comment by hdpero** [comment]
Note: [branch 1.0](https://github.com/titledk/silverstripe-uploaddirrules/tree/1.0) works fine on SS 3.2.* and SS 3.3.*

**Comment by anselmdk** [comment]
Petar, thanks for submitting this. Do you think this could have something to do with this one:
https://github.com/silverstripe/silverstripe-cms/issues/1398

I'm myself running the module on `3.3.x`, and am not experiencing it this issue. Overall though I see it doesn't make much sense for the module to save 2 versions...

**Comment by hdpero** [comment]
I'll look in to that and get back to you. Thanks!

**Comment by hdpero** [comment]
Hi,
yes solution is fixed on SS 3.3.x-dev , but problem with is that's no production tested and stable release. Do you know is there plan to include that fix in next SS release?

**Comment by anselmdk** [comment]
Great to hear!
Yes, I think it'll be both in the next `3.2.x` and the next `3.3.x` release.
